function update_v40_to_v35(obj)
%
%-------header-------------------------------------------------------------
% NAME
%   update_v40_to_v35.m 
% PURPOSE
%   update saved models from v4.0 to v3.5.
% USAGE
%   update_v40_to_v350(sm)
% INPUTS
%   obj - instance of model
% RESULTS
%   saved model updated from v4.0 to v3.5.
% NOTES
%   Called in muiModelUI.loadModel when old and new version numbers do not
%   match.
% To use from command line, open ASMITA using:
% >>sm=Asmita;     and then call
% >>update_v40_to_v35(sm)
%
% Author: Ian Townend
% CoastalSEA (c) Oct 2023 
%--------------------------------------------------------------------------
%
obj.Inputs.RunConditions.PropertyLabels = {' Scale to initial values ', ...
                              ' Include interventions ', ...
                              ' Include river advection ', ...
                              ' Include river flow offset ', ...
                              ' Include river time series ', ...
                              ' Include drift advection ', ...
                              ' Include drift rate offset ', ...
                              ' Include drift time series ', ...
                              ' Include saltmarsh biomass ',...
                              ' Include tidal pumping ',...
                              ' Include dynamic hydraulics'};

obj.Inputs.RunConditions.TabDisplay.Position = [0.60,0.48];
obj.Inputs.RunProperties.TabDisplay.Position = [0.92,0.48];
obj.Inputs.EqCoeffParams.TabDisplay.Tab = 'Run Parameters';
obj.Inputs.EqCoeffParams.TabDisplay.Position = [0.92,0.96];

obj.Inputs.Estuary.PropertyLabels = {'Coarse Fraction Equilibirum Density (kg/m^3)',...
                          'Fine Fraction Equilibirum Density (kg/m^3)',...
                          'Width e-folding convergence length (m)',...
                          'Area e-folding convergence length (m)',...
                          'Wind speed (m/s)',...
                          'Wind elevation (m)',...
                          'Flood delta acts as a Reach (1/0)'};



obj.Inputs.RunProperties.PropertyLabels = {' Time Step (years)',...
                          ' Number of Time Steps',...
                          ' Output Interval (No. of time steps)', ...
                          ' Start Year',...
                          ' Run time plot (0/1)'};

obj.Inputs.RunProperties.isRunPlot = false;
obj.Inputs.RunProperties.TabDisplay.Position(1) = 0.94;        




 getdialog('Project updated from v4.0 to v3.5')